Repository 5am-code/laravel-notion-api, pull requests merged in 2023-02, with the labels that each got.

#87 Search Endpoint: Fix cursor not passed correctly
  src/Endpoints/Search.php
Labels: fix, tests-required

#103 polish page and properties
  src/Entities/Page.php
  src/Entities/Properties/Date.php
  src/Entities/Properties/Text.php
  src/Entities/Properties/Title.php
  tests/EndpointPagesTest.php
  tests/PagePropertyTest.php
Labels: enhancement, fix

#95 NotionException: Use status from http response #88 additions
  src/Exceptions/NotionException.php
  tests/EndpointBlocksTest.php
  tests/EndpointDatabaseTest.php
  tests/EndpointPagesTest.php
  tests/EndpointSearchTest.php
  tests/EndpointUsersTest.php
  tests/NotionExceptionTest.php
Labels: enhancement
