Repository 5am-code/laravel-notion-api, pull requests merged in 2023-04, with the labels that each got.

#97 features, refactoring and fixes for 1.0.0
  .github/workflows/main.yml
  CONTRIBUTING.md
  README.md
  composer.json
  composer.lock
  src/Endpoints/Comments.php
  src/Endpoints/Database.php
  src/Endpoints/Endpoint.php
  src/Endpoints/Search.php
  src/Entities/Blocks/Block.php
  src/Entities/Collections/CommentCollection.php
  src/Entities/Comment.php
  src/Entities/Database.php
  src/Entities/Entity.php
  src/Entities/Page.php
  src/Entities/Properties/Date.php
  src/Entities/Properties/Property.php
  src/Entities/Properties/Text.php
  src/Entities/Properties/Title.php
  src/Entities/PropertyItems/SelectItem.php
  src/Entities/User.php
  src/Exceptions/NotionException.php
  src/Notion.php
  src/Query/Filters/Filter.php
  src/Query/Filters/FilterBag.php
  src/Query/Filters/Operators.php
  src/Query/Sorting.php
  src/Traits/HasArchive.php
  src/Traits/HasParent.php
  src/Traits/HasTimestamps.php
  tests/EndpointBlocksTest.php
  tests/EndpointCommentsTest.php
  tests/EndpointDatabaseTest.php
  tests/EndpointDatabasesTest.php
  tests/EndpointPagesTest.php
  tests/EndpointSearchTest.php
  tests/EndpointUsersTest.php
  tests/FilterBagTest.php
  tests/FilterTest.php
  tests/NotionApiTest.php
  tests/NotionExceptionTest.php
  tests/PagePropertyTest.php
  tests/Pest.php
  tests/SortingTest.php
  tests/stubs/endpoints/blocks/response_specific_block_200.json
  tests/stubs/endpoints/comments/response_create_comment_200.json
  tests/stubs/endpoints/comments/response_create_comment_403.json
  tests/stubs/endpoints/comments/response_create_comment_404.json
  tests/stubs/endpoints/comments/response_list_comments_200.json
  tests/stubs/endpoints/comments/response_list_comments_403.json
  tests/stubs/endpoints/comments/response_list_comments_404.json
  tests/stubs/endpoints/databases/response_specific_200.json
  tests/stubs/endpoints/pages/response_specific_200.json
Labels: WTD

#133 fix null error during creation of NotionException
  src/Exceptions/NotionException.php
Labels: fix

#129 Do not serialize scalar values
  src/Entities/Properties/Property.php
Labels: tests-required
